### ISSUE TITLE
ArgumentError: key must be 16 bytes when key is assigned to cipher

### ISSUE THREAD

**Issue by johaned** [epayco/epayco-ruby#7]
Hi, Epayco gave me a 32 bytes private key, but the cipher is using this mode `AES-128-CBC`, when the gem tries to execute the encryption process the cipher raises an error with *key must be 16 bytes*. OpenSSL since may 2016 is rejecting too long values in key/IV assignment...

curious thing is that the tests are also using a 32 bytes key, but I couldn't run the tests neither

what should I do, should I use `AES-256-CBC` mode or perhaps another codification for the key

any help is really appreciated

**Comment by caangos** [comment]
I have the same issue, any solution?

**Comment by johaned** [comment]
I used another communication channel and now, they are working on it as a high priority issue, I understand that we have a solution soon

**Comment by roberto-epayco** [comment]
The issue was fixed on this commit: https://github.com/epayco/epayco-ruby/commit/b8c6c923dcf9f479cd1ec4d3efe3622897b5c89e.
